// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = string
  })
}
variable "aws_region" {
  type = string
}
variable "enable_flow_logs" {
  type    = bool
  default = false
}
variable "high_availability" {
  type    = bool
  default = true
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "monitoring" {
  type = object({
    mode = optional(string)
    alarms = optional(object({
      ip_address_utilization = optional(object({
        percent = number
      }))
      nat_gateway_port_allocation = optional(object({
        count = number
      }))
    }))
  })
  default = null
}
variable "network" {
  type = object({
    automatic = optional(bool)
    mask      = optional(number)
    cidr      = optional(string)
  })
}
